# Generated by Django 5.0.6 on 2024-12-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='created_dt',
            field=models.DateTimeField(),
        ),
    ]
