# Generated by Django 5.0.6 on 2024-12-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_flashcardset_created_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='correct_anwser_given',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user_answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
