# Generated by Django 5.0.6 on 2024-12-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcard_correct_anwser_given_flashcard_user_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='correct_anwser_given',
            new_name='correct_answer_given',
        ),
    ]
