# Generated by Django 5.0.6 on 2025-01-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_rename_correct_anwser_given_flashcard_correct_answer_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='audio_filepaths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='selected_audio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
