# Generated by Django 5.0.6 on 2025-01-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_flashcard_audio_filepaths_flashcard_selected_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='audio_answer',
            field=models.FileField(null=True, upload_to='audio'),
        ),
    ]
