# Generated by Django 5.0.6 on 2025-01-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_flashcard_audio_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
