# Generated by Django 5.0.6 on 2025-02-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0008_alter_flashcard_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
