# Generated by Django 5.0.6 on 2024-12-01 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.TextField(max_length=100)),
                ('translation', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('created_dt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_dt'],
                'unique_together': {('user', 'text')},
            },
        ),
    ]
