# Generated by Django 5.0.6 on 2024-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='translation',
            field=models.TextField(max_length=300),
        ),
    ]
