# Generated by Django 5.0.6 on 2024-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0002_alter_phrase_category_alter_phrase_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
