# Generated by Django 5.0.6 on 2025-01-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0003_phrase_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ['text']},
        ),
    ]
