# Generated by Django 5.0.6 on 2025-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0004_alter_phrase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='transliteration',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='translation',
            field=models.CharField(max_length=400),
        ),
    ]
