# Generated by Django 5.0.6 on 2024-12-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('revelation_place', models.TextField(max_length=100)),
                ('revelation_order', models.IntegerField()),
                ('bismillah_pre', models.BooleanField()),
                ('name_complex', models.TextField(max_length=100)),
                ('name_arabic', models.TextField(max_length=100)),
                ('name_simple', models.TextField(max_length=100)),
                ('verses_count', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TranslatedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.TextField(default='english', max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_name', to='quran.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('verse_number', models.IntegerField()),
                ('verse_key', models.CharField(max_length=30)),
                ('juz_number', models.IntegerField()),
                ('hizb_number', models.IntegerField()),
                ('rub_el_hizb_number', models.IntegerField()),
                ('ruku_number', models.IntegerField()),
                ('manzil_number', models.IntegerField()),
                ('sajdah_number', models.IntegerField(blank=True, null=True)),
                ('page_number', models.IntegerField()),
                ('text_uthmani', models.TextField()),
                ('image_url', models.TextField(max_length=500)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('resource_id', models.IntegerField()),
                ('text', models.TextField()),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='quran.verse')),
            ],
        ),
    ]
