# Generated by Django 5.0.6 on 2024-12-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_alter_translation_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='selected_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
