# Generated by Django 5.0.6 on 2024-12-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_verse_selected_translation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translation',
            new_name='VerseTranslation',
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('audio_url', models.TextField()),
                ('text_uthmani', models.TextField()),
                ('text', models.TextField()),
                ('page_number', models.IntegerField()),
                ('line_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('verse_key', models.CharField(max_length=30)),
                ('char_type_name', models.CharField(max_length=30)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran.verse')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quran.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordTransliteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transliterations', to='quran.word')),
            ],
        ),
    ]
