# Generated by Django 5.0.6 on 2024-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_rename_translation_versetranslation_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio_url',
            field=models.TextField(null=True),
        ),
    ]
