# Generated by Django 5.0.6 on 2024-12-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_alter_word_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quran.verse'),
        ),
    ]
