# Generated by Django 5.0.6 on 2024-12-16 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_alter_word_verse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtranslation',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='quran.word'),
        ),
        migrations.AlterField(
            model_name='wordtransliteration',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transliteration', to='quran.word'),
        ),
    ]
