# Generated by Django 5.0.6 on 2025-01-07 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_alter_wordtranslation_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('language', models.TextField()),
                ('name', models.TextField()),
                ('englishName', models.TextField()),
                ('format', models.TextField()),
                ('type', models.TextField()),
                ('direction', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostedVerseAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.TextField()),
                ('audio_secondary_path', models.TextField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quran.audioedition')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quran.verse')),
            ],
        ),
    ]
