# Generated by Django 5.0.6 on 2025-01-07 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0008_audioedition_hostedverseaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='selected_audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostedverseaudio',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio', to='quran.verse'),
        ),
    ]
