# Generated by Django 5.0.6 on 2025-01-09 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0010_rename_englishname_audioedition_english_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_verse_id', models.IntegerField()),
                ('end_verse_id', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_selection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_verse_id'],
            },
        ),
    ]
