# Generated by Django 5.0.6 on 2025-01-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0011_verseselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='verseselection',
            name='end_chapter_id',
            field=models.IntegerField(default=114),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verseselection',
            name='juz_number',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verseselection',
            name='start_chapter_id',
            field=models.IntegerField(default=112),
            preserve_default=False,
        ),
    ]
