# Generated by Django 5.0.6 on 2025-02-26 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_tests_completed', models.IntegerField(blank=True, null=True)),
                ('correct_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('strongest_chapter', models.CharField(blank=True, max_length=70, null=True)),
                ('weakest_chapter', models.CharField(blank=True, max_length=70, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
                ('correct_answer_given', models.BooleanField(null=True)),
                ('flashcard_id', models.IntegerField(null=True)),
                ('included_in_stats', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50, null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='scorecard.scorecard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
                ('correct_answer_given', models.BooleanField(null=True)),
                ('flashcard_id', models.IntegerField(null=True)),
                ('included_in_stats', models.BooleanField(default=False)),
                ('chapter_id', models.IntegerField(null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='scorecard.scorecard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerseSelectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
                ('correct_answer_given', models.BooleanField(null=True)),
                ('flashcard_id', models.IntegerField(null=True)),
                ('included_in_stats', models.BooleanField(default=False)),
                ('chapter_id', models.IntegerField(null=True)),
                ('verse_selection_id', models.IntegerField(null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='scorecard.scorecard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
                ('correct_answer_given', models.BooleanField(null=True)),
                ('flashcard_id', models.IntegerField(null=True)),
                ('included_in_stats', models.BooleanField(default=False)),
                ('chapter_id', models.IntegerField(null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='scorecard.scorecard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
