# Generated by Django 5.0.6 on 2025-03-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='strongest_chapter',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='weakest_chapter',
        ),
    ]
